// <auto-generated />
using System;
using Back_End_school_To_Do_List.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Back_End_school_To_Do_List.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20220530065916_add-migration testmigration")]
    partial class addmigrationtestmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Back_End_school_To_Do_List.Models.Database.Lijstentable", b =>
                {
                    b.Property<int>("IdLijst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NaamLijst")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdLijst");

                    b.HasIndex(new[] { "NaamLijst" }, "IX_Lijstentable")
                        .IsUnique();

                    b.ToTable("Lijstentable");
                });

            modelBuilder.Entity("Back_End_school_To_Do_List.Models.Database.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("Duur")
                        .HasColumnType("int");

                    b.Property<string>("Lijst")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Naam")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Lijst");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Back_End_school_To_Do_List.Models.Database.Tasks", b =>
                {
                    b.HasOne("Back_End_school_To_Do_List.Models.Database.Lijstentable", "LijstNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("Lijst")
                        .HasConstraintName("FK_Tasks_Lijstentable")
                        .HasPrincipalKey("NaamLijst");

                    b.Navigation("LijstNavigation");
                });

            modelBuilder.Entity("Back_End_school_To_Do_List.Models.Database.Lijstentable", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
